### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by labvit** [nvpopov/qppcad#5]
There is any way to set custom white color?

**Comment by nvpopov** [comment]
You need to use **bg** function from Python console.

For example, you can change background color of the current workspace to red.
`>>> bg(1,0,0)`

There are two overloaded variants of this function:
    1. bg(arg0: qpp::generic_matrix<float, 3, 1>) -> None
    2. bg(arg0: float, arg1: float, arg2: float) -> None

**Comment by nvpopov** [comment]
You may also use "bg" property of class workspace_t from Python console.
`>>> ws[3].bg = pq.vector3f(1,0,1)`

This feature introduced in 5bc780d.

**Comment by nvpopov** [comment]
![wsbg](https://user-images.githubusercontent.com/342599/56373761-42337200-6234-11e9-8787-a4e14799052e.png)
