### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by labvit** [nvpopov/qppcad#6]
The menu item Tools->Generic tools->Structure similarity cause segfault when any xyz file is imported.

[Sat Apr 13 00:33:08 2019] DEBUG: object_inspector_widget_t::cur_ws_changed
[Sat Apr 13 00:33:08 2019] DEBUG: obj_insp_widget_t::cur_ws_selected_item_changed
[Sat Apr 13 00:33:08 2019] DEBUG ::cur_ws_selected_item_changed(), [num_wsi = 1]
[Sat Apr 13 00:33:08 2019] main_window::workspaces_changed_slot(), total ws = 1
[Sat Apr 13 00:33:08 2019] M_LAST_DIR= /media/vit/6dd540d6-27bf-4c7c-ad56-f2417288ac37/docs
[Sat Apr 13 00:33:08 2019] main_window::workspaces_changed_slot(), total ws = 1
QXcbConnection: XCB error: 3 (BadWindow), sequence: 3247, resource id: 15151365, major code: 40 (TranslateCoords), minor code: 0
/tmp/.mount_qppcady50d8a/AppRun: line 6: 15523 Segmentation fault      (core dumped) "${HERE}"/usr/bin/qppcad "$@"

**Comment by nvpopov** [comment]
Fixed in d12b8c97b167456173804eaa036bcab50ee331cb
